name: Release to python pip

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: github.actor == 'namaggarwal' && startsWith(github.event.issue.title, 'Release ') && github.event.comment.body == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: check-release
        with:
          text: ${{ github.event.issue.title }}
          regex: '^Release (\d\.\d)$'
      - name: print stuff
        run: |
          echo ${{ steps.regex-match.outputs.match }}
          echo ${{ steps.regex-match.outputs.group1 }}
          echo ${{ github.event.issue.title }}
          echo ${{ github.event.sender.login }}
          echo ${{ github.event.comment.body }}

