name: Release to python pip

on:
  issue_comment:
    types: [created]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: print stuff
        run: |
          echo ${{ github.event.issue.title }}
          echo ${{ github.event.sender.login }}
          echo ${{ github.event.comment.body }}

