name: Release to python pip

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{ github.actor == "namaggarwal" && startsWith(github.event.issue.title, "Release ") && github.event.comment.body == "release"  }}
    runs-on: ubuntu-latest
    steps:
      - name: print stuff
        run: |
          echo ${{ github.event.issue.title }}
          echo ${{ github.event.sender.login }}
          echo ${{ github.event.comment.body }}

