name: Release to python pip

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: github.actor == 'namaggarwal' && startsWith(github.event.issue.title, 'Release ') && github.event.comment.body == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: check-release
        with:
          text: ${{ github.event.issue.title }}
          regex: '^Release (\d\.\d\.\d)$'
      - name: Notify user starting the release
        if: ${{ steps.check-release.outputs.group1 != ''}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: +1
      - name: Checkout version ${{ steps.check-release.outputs.group1 }}
        if: ${{ steps.check-release.outputs.group1 != ''}}
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.check-release.outputs.group1 }}
      - name: Notify user of successful release
        if: ${{ steps.check-release.outputs.group1 != ''}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: hooray


