name: Release to python pip

on:
  issues:
    type: [ labeled ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: print stuff
        run: |
          echo ${{ github.event.sender.login }}
